trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'
    Python312:
      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-cov pytest-azurepipelines
    pytest --cov=. --cov-report=xml --cov-report=cobertura --cov-report=html --junitxml=pytest-results.xml
  displayName: 'Run tests with coverage'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFiles: '**/pytest-results.xml'
    testResultsFormat: 'JUnit'
    failTaskOnFailedTests: true

- task: PublishCodeCoverageResults@2
  displayName: 'Publish code coverage to Azure DevOps'
  inputs:
    summaryFileLocation: 'coverage.xml'


- task: PublishBuildArtifacts@1
  displayName: 'Publish HTML coverage artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/htmlcov'
    ArtifactName: 'CoverageReport'
    publishLocation: 'Container'
